server:
  port: 8082

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-g
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.notification.Notification.dto.JobCompletionEvent
        spring.json.trusted.packages: com.notification.Notification.dto,com.example.batch.dto
        spring.json.type.mapping: com.example.batch.dto.JobCompletionEvent:com.notification.Notification.dto.JobCompletionEvent

  mail: #im using MailHog here
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

  # Optional encoding setting
  default-encoding: UTF-8

kafka:
  topic:
    batch:
      completion: batch-job-topic

notification:
  email:
    recipient: fake@gmail.com